name: Employee Management CI/CD Pipeline

on:
  push:
    branches:
      - main 
    paths-ignore:
      - '.github/workflows/alb-permission-test.yml'
      
jobs:
  
  build:
    permissions:
      contents: read
      id-token: write
      

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4      

      - name: setup java
        uses: actions/setup-java@v4
        with:
           java-version: '25'
           distribution: 'temurin'

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v2
             
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Test AWS access
        run: |
             aws sts get-caller-identity
             aws elbv2 describe-target-health \
             --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}"      

      - name: make maven executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests   

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: employee-management-app  
          path: target/*.jar

      - name: Detach server 1 from ALB
        run: |
          echo "Detaching server 1 from ALB..."
          aws elbv2 deregister-targets \
            --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
            --targets Id="${{ secrets.BACKEND_1_INSTANCE_ID }}"
            
            

      - name: copy artifact to server 1
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.BACKEND_1_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          source: "target/*.jar"
          target: "/tmp"

      - name: Moving Jar to Release Directory on Server 1
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.BACKEND_1_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Checking Jar file path in /tmp directory..."
            JAR_FILE=$(find /tmp -name "*.jar" | head -n 1)
            if [ -z "$JAR_FILE" ]; then
             echo "ERROR: No JAR file found on /tmp!"
             exit 1
            fi
            echo "Found JAR file: $JAR_FILE on the server. Moving to /opt/employee-app/releases directory..."
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            Release_name="employee-management-${TIMESTAMP}.jar"
            sudo mkdir -p /opt/employee-app/releases
            sudo mv "$JAR_FILE" /opt/employee-app/releases/$Release_name 
            sudo ln -sfn /opt/employee-app/releases/$Release_name /opt/employee-app/current.jar
            sudo chown appuser:appuser /opt/employee-app/releases/$Release_name
            echo "Jar file moved successfully."

      - name: Verifying Deployment on Server 1
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.BACKEND_1_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Deployment successful. Verifying the JAR..."
            echo "Listing the contents of /opt/employee-app/releases directory:"
            sudo -u appuser ls -l /opt/employee-app/releases

      - name: Restarting Application Service on Server 1
        id: deploy_server_1
        continue-on-error: true
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_1_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
             echo "----------------------------------------"
             echo "Restarting the application service..."
             echo "----------------------------------------"

             sudo systemctl restart employee_app

              echo "Waiting for application to become healthy..."

             for i in {1..6}; do
               if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
                  echo "✅ Application is healthy."
                 break
               fi
                echo "Attempt $i/6 - Application not ready. Waiting..."
                sleep 5
                done

               if ! curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
                   echo "ERROR: ❌ Application is not healthy."
                    echo "==============================================="
                    echo "Deployment failed."
                    echo "==============================================="

                    echo "Last 30 lines of application logs:"
                    sudo journalctl -u employee_app --no-pager --lines=30

                    echo "==============================================="
                    echo "Initiating rollback to previous release..."

                    Rollback_jar=$(cd /opt/employee-app/releases && ls *.jar | sed -n '2p')
                    echo "Rolling back to previous release: $Rollback_jar"

                 if /opt/employee-app/rollback.sh "$Rollback_jar"; then
                    echo "✅ Rollback completed successfully."
                 else
                     echo "ERROR: ❌ Rollback failed!"
                     exit 1
                 fi

                 exit 1
               fi

               sudo systemctl status employee_app --no-pager --lines=20

               echo "==============================================="
               echo "✅ Application service restarted successfully."
               echo "==============================================="
      - name: Attach server 1 back to ALB After Successfull Rollback
        if: steps.deploy_server_1.outcome == 'failure'
        run: |
          echo "==============================================="
          echo "Rollback was performed. Attaching server 1 back to ALB..."
          echo "==============================================="
          aws elbv2 register-targets \
            --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
            --targets Id="${{ secrets.BACKEND_1_INSTANCE_ID }}"

      - name: Wait for server 1 to become healthy in ALB after Rollback
        if: steps.deploy_server_1.outcome == 'failure'
        run: |
          echo "Waiting for server 1 to become healthy in ALB..."
          for i in {1..12}; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
              --targets Id="${{ secrets.BACKEND_1_INSTANCE_ID }}" \
              --query 'TargetHealthDescriptions[0].TargetHealth.State' \
              --output text)
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "✅ Server 1 is healthy in ALB."
              break
            else
             echo "Attempt $i/12 - Server 1 not healthy. Current status: $HEALTH_STATUS. Waiting..."
             sleep 10
            fi
          done
          if [ "$HEALTH_STATUS" != "healthy" ]; then
            echo "ERROR: ❌ Server 1 did not become healthy in ALB within the expected time. after rollback."
            exit 1
          fi

      - name: Stop deployment after Server 1 failure
        if: steps.deploy_server_1.outcome == 'failure'
        run: |
          echo "==============================================="
          echo "❌ Server 1 deployment failed."
          echo "✅ Rollback completed."
          echo "✅ Server 1 is healthy in ALB after rollback."
          echo "🛑 Stopping deployment."
          echo "Server 2 will NOT be deployed."
          echo "==============================================="
          exit 1
      - name: Attach server 1 back to ALB
        if: steps.deploy_server_1.outcome == 'success'
        run: |
          echo "Attaching server 1 back to ALB..."
          aws elbv2 register-targets \
            --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
            --targets Id="${{ secrets.BACKEND_1_INSTANCE_ID }}" 

      - name: Wait for server 1 to become healthy in ALB
        if: steps.deploy_server_1.outcome == 'success'
        run: |
          echo "Waiting for server 1 to become healthy in ALB..."
          for i in {1..12}; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
              --targets Id="${{ secrets.BACKEND_1_INSTANCE_ID }}" \
              --query 'TargetHealthDescriptions[0].TargetHealth.State' \
              --output text)
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "✅ Server 1 is healthy in ALB."
              break
            fi
            echo "Attempt $i/12 - Server 1 not healthy. Current status: $HEALTH_STATUS. Waiting..."
            sleep 10
          done
          if [ "$HEALTH_STATUS" != "healthy" ]; then
            echo "ERROR: ❌ Server 1 did not become healthy in ALB within the expected time."
            exit 1
          fi

      - name: cleanup old releases on Server 1
        if: steps.deploy_server_1.outcome == 'success'
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.BACKEND_1_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Checking total jar count in your release Directory and cleaning up old releases if necessary..."
            RELEASE_DIR="/opt/employee-app/releases"
            RELEASE_COUNT=$(ls "$RELEASE_DIR"/*.jar 2>/dev/null | wc -l)
            echo "Total Jar Count: $RELEASE_COUNT"
            if [ "$RELEASE_COUNT" -gt 5 ]; then
               echo "More than 5 jars found. Cleaning up old releases..."
               echo "Deleting the following releases:"
               ls "$RELEASE_DIR"/*.jar | sort | head -n -5
               ls "$RELEASE_DIR"/*.jar | sort | head -n -5 | xargs sudo rm 
               echo "Cleanup completed."
               echo "Remaining releases:"
               ls -1 "$RELEASE_DIR"/*.jar
            else
               echo "Cleanup not required."
            fi
      - name: Detach server 2 from ALB
        run: |
          echo "Detaching server 2 from ALB..."
          aws elbv2 deregister-targets \
            --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
            --targets Id="${{ secrets.BACKEND_2_INSTANCE_ID }}"
      - name: copy artifact to server 2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.BACKEND_2_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          source: "target/*.jar"
          target: "/tmp"

      - name: Moving Jar to Release Directory on Server 2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_2_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Checking Jar file path in /tmp directory..."
            JAR_FILE=$(find /tmp -name "*.jar" | head -n 1)
            if [ -z "$JAR_FILE" ]; then
             echo "ERROR: No JAR file found on /tmp!"
             exit 1
            fi
            echo "Found JAR file: $JAR_FILE on the server. Moving to /opt/employee-app/releases directory..."
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            Release_name="employee-management-${TIMESTAMP}.jar"
            sudo mkdir -p /opt/employee-app/releases
            sudo mv "$JAR_FILE" /opt/employee-app/releases/$Release_name 
            sudo ln -sfn /opt/employee-app/releases/$Release_name /opt/employee-app/current.jar
            sudo chown appuser:appuser /opt/employee-app/releases/$Release_name
            echo "Jar file moved successfully."
  
      - name: Verifying Deployment on Server 2
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.BACKEND_2_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Deployment successful. Verifying the JAR..."
            echo "Listing the contents of /opt/employee-app/releases directory:"
            sudo -u appuser ls -l /opt/employee-app/releases
            
      - name: Restarting Application Service on Server 2
        id: deploy_server_2
        continue-on-error: true
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.BACKEND_2_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            
            echo "----------------------------------------"
            echo "Restarting the application service..."
            echo "----------------------------------------"
           
            sudo systemctl restart employee_app
            status=$?
           
            if [ $status -ne 0 ]; then
             echo "ERROR: ❌Failed to restart the application service. Please check the service logs for more details."
             echo "==============================================="
             echo "Restart failled not adding server 2 to ALB. Please check the logs for more details."
             echo "==============================================="
             exit 1
            fi
            echo "Waiting for application to become healthy..."
            for i in {1..6}; do
              if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
                echo "✅ Application is healthy."
                break
              fi
              echo "Attempt $i/6 - Application not ready. Waiting..."
              sleep 5
            done
            if ! curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "ERROR: ❌ Application is not healthy. Please check the service logs for more details."
              echo "Last 30 lines of application logs:"
              sudo journalctl -u employee_app --no-pager --lines=30
              echo "==============================================="
              echo "Deployment failled"
              echo "==============================================="              
              echo "Last 30 lines of application logs:"
              sudo journalctl -u employee_app --no-pager --lines=30
              echo "==============================================="
              echo "Initiating rollback to previous release..."
              Rollback_jar=$(ls /opt/employee-app/releases/*.jar | sed -n '2p')
              echo "Rolling back to previous release: $Rollback_jar"
              Rollback_jar=$(cd /opt/employee-app/releases && ls *.jar | sed -n '2p')
              echo "Rolling back to previous release: $Rollback_jar"
              if /opt/employee-app/rollback.sh "$Rollback_jar"; then
                 echo "Rollback completed successfully."
              else
                 echo "ERROR: Rollback failed!"
                 exit 1
              fi
              exit 1
            fi
            sudo systemctl status employee_app --no-pager --lines=20
            echo "==============================================="
            echo "✅ Application service restarted successfully."
            echo "==============================================="
      - name: Attach server 2 back to ALB After Successfull Rollback
        if: always() && steps.deploy_server_2.outcome == 'failure'
        run: |
          echo "==============================================="
          echo "Rollback was performed. Attaching server 2 back to ALB..."
          echo "==============================================="
          aws elbv2 register-targets \
            --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
            --targets Id="${{ secrets.BACKEND_2_INSTANCE_ID }}"

      - name: Wait for server 2 to become healthy in ALB after Rollback
        if: always() && steps.deploy_server_2.outcome == 'failure'
        run: |
          echo "Waiting for server 2 to become healthy in ALB..."
          for i in {1..12}; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
              --targets Id="${{ secrets.BACKEND_2_INSTANCE_ID }}" \
              --query 'TargetHealthDescriptions[0].TargetHealth.State' \
              --output text)
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "✅ Server 2 is healthy in ALB."
              break
            else
             echo "Attempt $i/12 - Server 2 not healthy. Current status: $HEALTH_STATUS. Waiting..."
             sleep 10
            fi
          done
          if [ "$HEALTH_STATUS" != "healthy" ]; then
            echo "ERROR: ❌ Server 2 did not become healthy in ALB within the expected time. after rollback."
            exit 1
          fi

      - name: Stop deployment after Server 2 failure
        if: always() && steps.deploy_server_2.outcome == 'failure'
        run: |
             echo "==============================================="
              echo "❌ Server 2 deployment failed."
             echo "✅ Rollback was attempted."
             echo "🛑 Stopping deployment."
             echo "==============================================="
             echo "Server 2 failed. Deployment pipeline will stop."
             echo "==============================================="
             exit 1

      - name: Attach server 2 back to ALB
        if: steps.deploy_server_2.outcome == 'success'
        run: |
          echo "Attaching server 2 back to ALB..."
          aws elbv2 register-targets \
            --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
            --targets Id="${{ secrets.BACKEND_2_INSTANCE_ID }}"
            
      - name: Wait for server 2 to become healthy in ALB
        if: steps.deploy_server_2.outcome == 'success'
        run: |
         echo "Waiting for server 2 to become healthy in ALB..."
         for i in {1..12}; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn "${{ secrets.TARGET_GROUP_ARN }}" \
              --targets Id="${{ secrets.BACKEND_2_INSTANCE_ID }}" \
              --query 'TargetHealthDescriptions[0].TargetHealth.State' \
              --output text)
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "✅ Server 2 is healthy in ALB."
              break
            fi
            echo "Attempt $i/12 - Server 2 not healthy. Current status: $HEALTH_STATUS. Waiting..."
            sleep 10    
          done
          if [ "$HEALTH_STATUS" != "healthy" ]; then
            echo "ERROR: ❌ Server 2 did not become healthy in ALB within the expected time."
            exit 1
          fi       
      - name: cleanup old releases on Server 2
        if: steps.deploy_server_2.outcome == 'success'
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.BACKEND_2_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Checking total jar count in your release Directory and cleaning up old releases if necessary..."
            RELEASE_DIR="/opt/employee-app/releases"
            RELEASE_COUNT=$(ls "$RELEASE_DIR"/*.jar 2>/dev/null | wc -l)
            echo "Total Jar Count: $RELEASE_COUNT"
            if [ "$RELEASE_COUNT" -gt 5 ]; then
               echo "More than 5 jars found. Cleaning up old releases..."
               echo "Deleting the following releases:"
               ls "$RELEASE_DIR"/*.jar | sort | head -n -5
               ls "$RELEASE_DIR"/*.jar | sort | head -n -5 | xargs sudo rm 
               echo "Cleanup completed."
               echo "Remaining releases:"
               ls -1 "$RELEASE_DIR"/*.jar
            else
               echo "Cleanup not required."
            fi        
          