name: Employee Management CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:


    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4      

      - name: setup java
        uses: actions/setup-java@v4
        with:
           java-version: '25'
           distribution: 'temurin'

      - name: make maven executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests   

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: employee-management-app  
          path: target/*.jar

      - name: copy artifact to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          source: "target/*.jar"
          target: "/tmp"

      - name: Moving Jar to Release Directory
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Checking Jar file path in /tmp directory..."
            JAR_FILE=$(find /tmp -name "*.jar" | head -n 1)
            if [ -z "$JAR_FILE" ]; then
             echo "ERROR: No JAR file found!"
             exit 1
            fi
            echo "Found JAR file: $JAR_FILE"
            sudo mkdir -p /opt/employee-app/releases
            sudo mv "$JAR_FILE" /opt/employee-app/releases/ 
            sudo chown appuser:appuser /opt/employee-app/releases/*.jar
            echo "Jar file moved successfully."

      - name: Verifying Deployment
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            echo "Deployment successful. Verifying the application..."
            echo "Listing the contents of /opt/employee-app/releases directory:"
            sudo -u appuser ls -lh /opt/employee-app/releases

      - name: Restarting Application Service
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            set -e
            echo "----------------------------------------"
            echo "Restarting the application service..."
            echo "----------------------------------------"
            set +e
            sudo systemctl restart employee-app
            status=$?
            if [ $status -ne 0 ]; then
              echo "ERROR: ❌Failed to restart the application service. Please check the service logs for more details."
              exit 1
            fi
            sleep 10 #for the service to restart properly
            sudo systemctl status employee_app --no-pager --lines=20
            echo "==============================================="
            echo "✅ Application service restarted successfully."
            echo "==============================================="

            